parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/*/Domain/{Entity,ValueObject,Constant}/'
            - '../src/*/Infrastructure/Doctrine/Types/'
            - '../src/Kernel.php'

    App\DataFixtures\:
        resource: '../fixtures/*'

    App\Core\Infrastructure\Api\Controller\:
        resource: '../src/Core/Infrastructure/Api/Controller/'
        tags: [ 'controller.service_arguments' ]

    App\Shared\Infrastructure\Doctrine\EventListener\LookupListener:
        tags:
            - { name: doctrine.event_listener, event: preFlush, priority: 400 }
            - { name: doctrine.event_listener, event: prePersist, priority: 400 }
